files:
  - source: /docs/**/*.md
    ignore:
      - public/
      - .vitepress/
    translation: /docs/%two_letters_code%/%original_file_name%
  - source: docs/.vitepress/i18n
    translation: /docs/.vitepress/i18n/%two_letters_code%.js
