files:
  - source: /**/*.md
    ignore:
      - CONTRIBUTING.md
      - Readme.md
    translation: /%two_letters_code%/%original_path%/%original_file_name%
  - source: .vitepress/i18n/zh.js
    translation: /.vitepress/i18n/%two_letters_code%.js
    multilingual: 1
  - source: .vitepress/i18n/sidebar/zh/*.js
    translation: /.vitepress/i18n/sidebar/%two_letters_code%/%original_file_name%
  - source: .vitepress/i18n/navbar/zh.js
    translation: /.vitepress/i18n/navbar/%two_letters_code%.js
    multilingual: 1
