name: Add labels to the PR initiated for Crowdin

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  check-and-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title and add labels
        uses: actions/github-script@v6
        with:
          script: |
            if (context.payload.pull_request.title.includes('New Crowdin updates')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: ['Crowdin', 'Feature']
              });
              console.log('Added Crowdin and Feature labels to the PR');
            } else {
              console.log('PR title does not match "New Crowdin updates", no labels added');
            }