name: Auto Assign PullRequests

on:
  pull_request:
    types: [opened]

jobs:
  assign-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Assign PR to QingFeng-awa
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: ['QingFeng-awa']
            })