name: Send a build request to the API

on:
  push:
    branches: [ v2 ]

env:
  PANEL_API_KEY: ${{ secrets.PANEL_API_KEY }}
  API_BASE_URL: ${{ secrets.API_BASE_URL }}

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Timestamp and Token
        id: auth
        run: |
          timestamp=$(date +%s)
          echo "TIMESTAMP=$timestamp" >> $GITHUB_ENV
          token=$(echo -n "1panel${{ env.PANEL_API_KEY }}${timestamp}" | md5sum | awk '{print $1}')
          echo "PANEL_TOKEN=$token" >> $GITHUB_ENV

      - name: Call API
        run: |
          api_url="${{ env.API_BASE_URL }}/api/v1/cronjobs/handle"
          
          response=$(curl -s -X 'POST' \
            "$api_url" \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H "1Panel-Token: ${{ env.PANEL_TOKEN }}" \
            -H "1Panel-Timestamp: ${{ env.TIMESTAMP }}" \
            -d '{"id": 10}')

          echo "API Response: $(echo "$response" | jq -c)"
          echo "$response" | jq -e '.code == 200' || exit 1