name: Send a build request to the API

on:
  push:
    branches: [ v2 ]

env:
  PANEL_API_KEY: ${{ secrets.PANEL_API_KEY }}
  API_BASE_URL: ${{ secrets.API_BASE_URL }}
  CRONJOB_ID: ${{ vars.CRONJOB_ID }}
  API_VERSION: ${{ vars.API_VERSION }}

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Timestamp and Token
        id: auth
        run: |
          timestamp=$(date +%s)
          token=$(echo -n "1panel${{ env.PANEL_API_KEY }}${timestamp}" | md5sum | awk '{print $1}')
          echo "::add-mask::$token"
          echo "PANEL_TOKEN=${token}" >> $GITHUB_ENV
          echo "TIMESTAMP=${timestamp}" >> $GITHUB_ENV

      - name: Call API (Secure Mode)
        run: |
          api_url="${{ env.API_BASE_URL }}/api/${{ env.API_VERSION }}/cronjobs/handle"
          response=$(curl -s -X 'POST' \
            "$api_url" \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H "1Panel-Token: ${{ env.PANEL_TOKEN }}" \
            -H "1Panel-Timestamp: ${{ env.TIMESTAMP }}" \
            -d '{"id": ${{ env.CRONJOB_ID }}}' 2>&1)
          code=$(echo "$response" | jq -r '.code')
          echo "API Response Code: $code"
          [ "$code" = "200" ] || exit 1
